# Generated by Django 3.0.5 on 2022-02-14 15:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.URLField(verbose_name='头像')),
                ('career', models.CharField(max_length=50, verbose_name='事业')),
                ('introduction', models.TextField(verbose_name='介绍')),
                ('skill_title', models.CharField(default='技能', max_length=50, verbose_name='技能标题')),
            ],
            options={
                'verbose_name': '关于',
                'verbose_name_plural': '关于',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类名称')),
                ('index', models.IntegerField(default=1, verbose_name='分类排序')),
                ('add_menu', models.BooleanField(default=False, verbose_name='添加到导航栏')),
                ('icon', models.CharField(default='fas fa-home', max_length=30, verbose_name='导航图标')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='标题')),
                ('url', models.URLField(blank=True, verbose_name='网址')),
                ('avatar', models.URLField(default='https://i.loli.net/2020/04/23/jGP8gQOYW75TSJp.png', verbose_name='头像')),
                ('desc', models.TextField(max_length=50, verbose_name='描述')),
                ('button_word', models.CharField(default='访问博客', max_length=10, verbose_name='跳转文字')),
            ],
            options={
                'verbose_name': '成员',
                'verbose_name_plural': '成员',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='公告栏标题')),
                ('content', models.TextField(max_length=500, verbose_name='公告内容')),
                ('icon', models.CharField(default='far fa-lightbulb', max_length=50, verbose_name='公告图标')),
            ],
            options={
                'verbose_name': '公告栏',
                'verbose_name_plural': '公告栏',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='苏格拉没有底', max_length=30, verbose_name='网站名字')),
                ('keywords', models.CharField(default='关键字测试', max_length=50, verbose_name='网站关键词')),
                ('logo', models.URLField(default='https://jwt1399.top/favicon.png', max_length=100, verbose_name='网站logo')),
                ('desc', models.CharField(max_length=50, verbose_name='网站描述')),
                ('slogan', models.CharField(max_length=50, verbose_name='网站标语')),
                ('dynamic_slogan', models.CharField(max_length=200, verbose_name='动态标语')),
                ('icp_number', models.CharField(max_length=40, verbose_name='备案号')),
                ('icp_url', models.URLField(default='http://www.beian.miit.gov.cn/', max_length=100, verbose_name='备案链接')),
                ('bg_cover', models.URLField(default='http://119.23.243.154/image/Covteam-hack.jpg', max_length=100, verbose_name='背景图片')),
            ],
            options={
                'verbose_name': '网站设置',
                'verbose_name_plural': '网站设置',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50, verbose_name='方向名')),
                ('skill_precent', models.CharField(default='%', max_length=50, verbose_name='百分比')),
            ],
            options={
                'verbose_name': '技能',
                'verbose_name_plural': '技能',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_url', models.URLField(verbose_name='社交链接')),
                ('social_desc', models.CharField(max_length=50, verbose_name='简介')),
                ('social_icon', models.CharField(default='fas fa-envelope', max_length=50, verbose_name='社交图标')),
            ],
            options={
                'verbose_name': '社交',
                'verbose_name_plural': '社交',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='标签名称')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Valine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(max_length=100, verbose_name='appId')),
                ('appkey', models.CharField(max_length=100, verbose_name='appKey')),
                ('avatar', models.CharField(blank=True, default='', max_length=100, verbose_name='avatar')),
                ('pagesize', models.IntegerField(default='10', verbose_name='pageSize')),
                ('placeholder', models.CharField(max_length=100, verbose_name='placeholder')),
            ],
            options={
                'verbose_name': 'valine评论',
                'verbose_name_plural': 'valine评论',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('author', models.CharField(blank=True, default='DRK', max_length=10, null=True, verbose_name='作者')),
                ('desc', models.CharField(max_length=50, verbose_name='文章描述')),
                ('cover', models.URLField(default='https://i.loli.net/2020/04/23/lJLjEtbs2NFwynQ.jpg', verbose_name='文章封面')),
                ('content', mdeditor.fields.MDTextField(verbose_name='文章内容')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='阅读量')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='文章分类')),
                ('tag', models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='文章标签')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ('-add_time',),
            },
        ),
    ]
